### ISSUE TITLE
case sensitive wallet bug in the keystore

### ISSUE THREAD

**Issue by jparicka** [jparicka/phoenix-22#6]
root@spark-devel:/opt/phoenix-22# ls -la keystore/
0x0a141dbbdd829fadc7fe37bb0eef6199fd9a7ae4.json  0xa69764fd77ded06c583601f3a7c746d22258b1c3.json
0x10e49d45596545710e85972b8a35c4568b996ef0.json  0xa99c25e6bf406a6f38479fcce66d75b8b0eb190e.json
0x147c1910158338df88733ea408111f56399341ca.json  0xaa3d91b887dc220b1fde1b8012e33871c20576c0.json
0x191d92a9d210f8a7fc338c47c67efd9692b4a17e.json  0xc1b4a851a704976e76345e23017b10daa109429a.json
0x2ac7d36b3a9d86ecef3d0e797918d3071af1d855.json  0xc527f25fd31ab34c370258680391dfeaf6d478d4.json
0x2edcf67e68811950000244bb3572125df5b22f43.json  0xcad689aee313579fac675f0bb8019eb91cb9535a.json
0x344f981edf58ee9d5963627b96197a746e5a978d.json  0xcb1a2d856f48c191a290e3dd22df266f56649eaa.json
0x355385af1e3bd1c72f83cb8be0eab4012f66ceed.json  0xcd1f62af69626459c3b2ad7e52ead54128542bd8.json
0x362107994fdec7970703d9d6cb13e2610ffffadc.json  0xd0094c1ed7298271400bc37104f315540575ea7c.json
0x41ef2c5e62e10bd08391ddd7b4ef450bb4b150da.json  0xd0ba7d27119cc002e9052220d4c98a8764d066bd.json
0x45c27eb796836b4f1bb8bbbfcd422fb0f008854c.json  0xd6a9aa2c9534805e996cbc63bce93ec390b7715d.json
0x4e09054200688e2286ade60aa4b82f9a0a617127.json  0xde5f3cc3e4431c5939d84eefc6ad9e3565f02b8e.json
0x5228242a58a985a33f0a5c287184c1536ccefd34.json  0xdea5fac5838db5b4069e351f0949d91dcf9156a8.json
0x571ee8a1cdb1390a6d1d83aa8f9c66f0d2b4ed0f.json  0xdf19b2b7a59475ea957e824b6fbc142550120ede.json
0x598f5a90245b31b522b530e93ab681af7db8ed9b.json  0xe3de68f431e512df4e8f4361e817071a93403687.json
0x6399440a019a4f1ec15896530d1ecaed9265680d.json  0xe4c2ed9ed4202d6947746c03e37e915ad773b3f4.json
0x6688444b649c255923ed38e392d954279e6af064.json  0xe53f69fb8d9eca828f43b4a48fc0af4a2f57efaa.json
0x68ae2364557ce92d9287f72786350839c73139e9.json  0xf70a50360950de0c608bf216539e20c09cd27d56.json
0x73bcf71457837a64db5d0b46b5dbd3e45795b37b.json  0xfa4d955380b707892086a101dbff8a99023b6699.json
0x74fa0502f7a05e77868179ba8defaec9e04c7cea.json  0xfb61cc5105576856c71aa727bde658cad2899ea9.json
0x78dca886d0ac8d87931c0397fc755eaab663f28b.json  0xfed5000dc2edd6108a453655286159f7ee12e3d2.json
0x85ae6eb58fb1c93a1476d524c0c963a376ded11b.json  ._.DS_Store
0x8c4f18edd26315c8ac59e488f9f24ad22f12c25e.json  .DS_Store
0x958e0d4361651f7cfd1e2a3097e51958c552601a.json  robot-master-wallet.json
root@spark-devel:/opt/phoenix-22# ls -la keystore/0xcaD689aEE313579FaC675f0BB8019eB91CB9535A^C
root@spark-devel:/opt/phoenix-22#

**Comment by jparicka** [comment]
root@spark-devel:/opt/phoenix-22# python3 robot_betting_autoplay.py 
Autoplay bidding robot v0.1
Contract 0x7982277531c859a6e5f06ef78635dee99f5cc355

Placing new bets..
Traceback (most recent call last):
  File "robot_betting_autoplay.py", line 139, in <module>
    _place_bid(0.01, player)
  File "robot_betting_autoplay.py", line 47, in _place_bid
    with open('keystore/'+player.address+'.json') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'keystore/0xcaD689aEE313579FaC675f0BB8019eB91CB9535A.json'
root@spark-devel:/opt/phoenix-22# ls -la keystore/0xcaD689aEE313579FaC675f0BB8019eB91CB9535A.json
ls: cannot access 'keystore/0xcaD689aEE313579FaC675f0BB8019eB91CB9535A.json': No such file or directory
root@spark-devel:/opt/phoenix-22#

**Comment by jparicka** [comment]
fixed
